### ISSUE TITLE
Add ETH+wETH to list of tokens in My Wallet

### ISSUE THREAD

**Issue by fvictorio** [0xProject/0x-launch-kit-frontend#120]
The list of token balances should show have as its first row the total amount of ether (ETH + wETH). Also, de lock/unlock button should allow the user to lock/unlock its wETH.

This row will be different to the others, in the sense that its balance is actually the sum of two things. So adding the wETH token to the list of tokens won't be enough.

![Image 2019-03-09 at 4 11 26 PM](https://user-images.githubusercontent.com/1939415/54076091-06e17300-4286-11e9-8d25-8a5ec64effbf.png)

**Comment by pablofullana** [comment]
Updated description with Figma mockup screenshot.
