### ISSUE TITLE
Unhandled Rejection (Error): Expected tokenAddress to be of type string, encountered: undefined

### ISSUE THREAD

**Issue by angelorc** [0xProject/0x-launch-kit-frontend#132]
Hello,
I tried to test the frontend but I get the error in object

```
git clone https://github.com/0xProject/0x-launch-kit-frontend.git
yarn
yarn start
```

Then in browser
```
Unhandled Rejection (Error): Expected tokenAddress to be of type string, encountered: undefined

export const tokenToTokenBalance = async (token: Token, address: string): Promise<TokenBalance> => 
```

**Comment by Agupane** [comment]
This issue was solved time ago. There is also a [closed PR](https://github.com/0xProject/0x-launch-kit-frontend/pull/438) in which we display an error message to let the user know that the network is wrong.

In case you still have this problem, feel free to ping or open another issue.
