### ISSUE TITLE
"Cancel sale" button

### ISSUE THREAD

**Issue by fvictorio** [0xProject/0x-launch-kit-frontend#315]
Depends on #314.

Show a "Cancel Sale" button in the individual asset page for assets that belong to the current user and that are on sale.

There's no design for this. Let's assume that clicking it will show you a modal for confirming a transaction on the contract.

**Comment by mariano-aguero** [comment]
Created an issue for Dutch Auction
https://github.com/0xProject/0x-launch-kit-frontend/issues/463
