### ISSUE TITLE
Add price / market depth chart

### ISSUE THREAD

**Issue by pablofullana** [0xProject/0x-launch-kit-frontend#38]
![Image 2019-02-20 at 4.52.47 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58dbaada572686001a5bb236/125516c66e82c728ace21e0d46c1999b2487c3fbdfb8e60ef40fbdc6790626676950ed7e22cbb77fff725643434d0eee1e020a17b8eb8339a3e53970db5e02ef873c5e22c23511a8ee864ced07ba758c5d99a4fedb1294b7607caddecd5d340c041f83fe5830a09f42ca5bfe4fe64c51b65e.png)

**Comment by pablofullana** [comment]
hey @chriskalani. Provided mockups show TradingView charts. Is the decision to using these charts already made?

If so, I think we need to request the library to them. [HTML5 stock forex bitcoin charting library](https://www.tradingview.com/HTML5-stock-forex-bitcoin-charting-library/).

If not, do you have any alternatives in mind that we could take a look at?

**Comment by chriskalani** [comment]
Charts aren’t actually part of the spec for this. We’re open to discuss options post-launch


________________________________

**Comment by fvictorio** [comment]
Closing this for now.
