### ISSUE TITLE
My size do not display light dash on empty component

### ISSUE THREAD

**Issue by Agupane** [0xProject/0x-launch-kit-frontend#405]
“My size” in the order book should display a light dash instead of “0.0000”

**Comment by chriskalani** [comment]
It is worth mentioning that the Price and My Size columns should be switched as well to match the design:

<img width="403" alt="Screen Shot 2019-05-20 at 3 20 27 PM" src="https://user-images.githubusercontent.com/263522/58055559-f0238c00-7b12-11e9-9869-ce472363a9ec.png">
