### ISSUE TITLE
Metamask shouldn't prompt after every refresh

### ISSUE THREAD

**Issue by burnsben** [0xProject/0x-launch-kit-frontend#419]
Every time the page reloads, it shows the user the metamask connection prompt. 
<img width="428" alt="Screen Shot 2019-05-21 at 5 26 43 PM" src="https://user-images.githubusercontent.com/29830192/58139002-a6f43a80-7bed-11e9-8268-872ccf43da99.png">

**Comment by gabitoesmiapodo** [comment]
@burnsben  This shouldn't happen if `REACT_APP_ENABLE_NO_METAMASK_PROMPT='true'` is set in `.env`

Could you check it before we proceed?

@Agupane @mariano-aguero could you confirm this?

**Comment by burnsben** [comment]
Sounds good. For the final version this should be turned off by default.

**Comment by burnsben** [comment]
Looks like this is still an issue for the demos. Can we make sure this is off by default?
