### ISSUE TITLE
Improvements to Buy/Sell Flow modal

### ISSUE THREAD

**Issue by burnsben** [0xProject/0x-launch-kit-frontend#434]
Completed one more design pass on the buy/sell flow modal:
<img width="360" alt="Screen Shot 2019-05-22 at 4 33 54 PM" src="https://user-images.githubusercontent.com/29830192/58215613-8ab8d200-7caf-11e9-97e7-f4e8358af9c2.png">

List of changes
-positioning of title, paragraph copy and image have been shuffled around.
-Height of modal has increased to 420px
-Size of status graphics has increased (metamask icon, loading spinner, success and error)
-Title now updates to the current status of the buy/sell flow. The smaller text below the progress bars should now only read "Waiting for Confirmation", "Waiting for Signature", the estimated time, or should be blank(on success states)
-body/message copy should now be 14pt instead of 16pt(see design) 

You can pull the title/ body copy updates from this figma doc which show the latest on the design: https://www.figma.com/file/hTFxa4hVhZtbqdLZwPgc8P/Launch-Kit-ERC-20?node-id=157%3A6663

Additionally, I'm hoping we can limit the number of significant figures to 3 places after the decimal in this modal. 

The link should always be on a new line. 
<img width="371" alt="Screen Shot 2019-05-22 at 4 16 10 PM" src="https://user-images.githubusercontent.com/29830192/58216165-13387200-7cb2-11e9-89e6-b2ab8d0b4a4c.png">

**Comment by pablofullana** [comment]
@burnsben I deleted the second part of this issue's original description and opened a new to focus on it: #443
