### ISSUE TITLE
Hard Corners on the buy/sell panel tabs 

### ISSUE THREAD

**Issue by burnsben** [0xProject/0x-launch-kit-frontend#435]
<img width="570" alt="Screen Shot 2019-05-22 at 11 16 31 PM" src="https://user-images.githubusercontent.com/29830192/58229899-b5bf1800-7ce7-11e9-9c74-556209bc1b96.png">
looks like the background isn't rounded here.

**Comment by burnsben** [comment]
looks like there might be a separate issue with the bottom left corner?

**Comment by mariano-aguero** [comment]
> looks like there might be a separate issue with the bottom left corner?

Done in the same PR. 

Regards
