### ISSUE TITLE
Enhance error messages

### ISSUE THREAD

**Issue by pablofullana** [0xProject/0x-launch-kit-frontend#443]
Also hoping the error message can give us more context about what went wrong. I think some error messages are around not having sufficient amounts? If the user doesn't have enough ETH or wETH, it should show an error message like this:

![image](https://user-images.githubusercontent.com/1939415/58283660-3846e680-7d7f-11e9-9f13-50fc1f2dd77d.png)

**Comment by burnsben** [comment]
We have this exact type of error message in our current version of 0x instant. Perhaps we can reuse existing components.

**Comment by burnsben** [comment]
While we're at it, I updated the design to use orange as the background color, and included an error icon

<img width="393" alt="Screen Shot 2019-05-23 at 1 56 52 PM" src="https://user-images.githubusercontent.com/29830192/58286022-b943b500-7d62-11e9-85a8-f814fd2e70c7.png">

**Comment by burnsben** [comment]
realizing I was inspired by (stole from) coinbase pro. 
Imagining this error will show after the button is clicked. The button will stay orange for 1-2 seconds, and the "you don't have enough ETH" message below will stay for 3-4 seconds. 

See coinbase as an example:
https://drive.google.com/file/d/1fzDp-laQGdKfBGfZw_HgyhvkstO27-9t/view?usp=sharing
