### ISSUE TITLE
Buy/Sell panel colors

### ISSUE THREAD

**Issue by burnsben** [0xProject/0x-launch-kit-frontend#444]
On both light and dark modes, we should use red and green for the buy and sell text and buttons. 

Red: #FF6534
Green: #3CB34F

<img width="508" alt="Screen Shot 2019-05-23 at 2 25 43 PM" src="https://user-images.githubusercontent.com/29830192/58287775-b6e35a00-7d66-11e9-89c2-63c8413180b5.png">

**Comment by fvictorio** [comment]
@burnsben should we change the colors of the buy and sell orders in the orderbook too?

**Comment by pablofullana** [comment]
Yes, change both colors in both places.
