### ISSUE TITLE
Erc721 Background Color Metadata

### ISSUE THREAD

**Issue by burnsben** [0xProject/0x-launch-kit-frontend#445]
Rarebits and open sea have predefined standards for background colors that many/most NFTs support. Would be great to retrieve it from those sources. 
See: https://docs.rarebits.io/reference
and https://docs.opensea.io/docs/2-adding-metadata for reference. 
And if not attainable, fall back on a standard light gray background color. 

Currently looks like we're showing random colors for these? Would prefer to use the metadata, or a consistent light gray instead of going for something more random. 
<img width="1387" alt="Screen Shot 2019-05-23 at 10 30 50 AM" src="https://user-images.githubusercontent.com/29830192/58287875-fb6ef580-7d66-11e9-808b-3121e7b524a0.png">

**Comment by Agupane** [comment]
Hi @burnsben, we are already using the background color from openSea (we use it on mainnet and rinkeby). For ganache we have hardcoded values. You can see the file with the hardcoded-color values [here](https://github.com/0xProject/0x-launch-kit-frontend/blob/development/src/services/collectibles_metadata_sources/mocked.ts) if you want.

Also, in case openSea does not provides a background color  we closed [this PR](https://github.com/0xProject/0x-launch-kit-frontend/pull/386) for adding a fallback one. The default value is `#FFF`. If you wan't from us to change this default color please let me know.

**Comment by unjapones** [comment]
I forgot to assign this to @burnsben on Friday, as a reminder to pick a default fallback color different from `#FFF`.

**Comment by burnsben** [comment]
let's make the fallback color #EBF0F5

**Comment by burnsben** [comment]
This should be done in conjunction with changing the page background color: https://github.com/0xProject/0x-launch-kit-frontend/issues/481
