### ISSUE TITLE
Change Spacing on wallet page.

### ISSUE THREAD

**Issue by burnsben** [0xProject/0x-launch-kit-frontend#482]
This should match our mocks with 10px spacing between the convert panel and token balances panel.
<img width="608" alt="Screen Shot 2019-05-28 at 3 56 54 PM" src="https://user-images.githubusercontent.com/29830192/58517763-60f52480-8161-11e9-86b9-be0cd906e5f2.png">

**Comment by gabitoesmiapodo** [comment]
@burnsben 

Horizontal margin is currently 10px for columns. There's also the (barely noticeable on the dark theme) 1px card's border.

**Comment by gabitoesmiapodo** [comment]
@burnsben 

Forget my last comment, I could reproduce the bug. There's some margin overlapping there that I'll fix now.
