### ISSUE TITLE
Darken Tooltip Background

### ISSUE THREAD

**Issue by burnsben** [0xProject/0x-launch-kit-frontend#485]
This tooltip background should be darker than the panel. Change to the "form background" color on darkmode. #1B1B1B
<img width="257" alt="Screen Shot 2019-05-28 at 4 20 01 PM" src="https://user-images.githubusercontent.com/29830192/58518593-a49d5d80-8164-11e9-991f-58486a1ab69d.png">

**Comment by burnsben** [comment]
Looking at the change and realizing that it needs to go a bit darker. lets make it #000000. 
Sorry about that!

**Comment by gabitoesmiapodo** [comment]
Done.
