### ISSUE TITLE
Frontend supports only 18 decimal tokens

### ISSUE THREAD

**Issue by icinsight** [0xProject/0x-launch-kit-frontend#516]
If your token has something else than 18 decimals you'll get weird calculations in orders and balances. My Wallet renders correctly. These orders fail, of course.

![image](https://user-images.githubusercontent.com/39129866/58756757-2975d780-84d5-11e9-8415-2cccc70733a3.png)

**Comment by icinsight** [comment]
In this case "Wallet balance" shows 0.00 (it is 800 in reality) and "Trade Size" shows 20000000000 (the real one I managed to post was 2 tokens).

![image](https://user-images.githubusercontent.com/39129866/58756778-7e195280-84d5-11e9-9436-b0ea8d71c4c0.png)

![image](https://user-images.githubusercontent.com/39129866/58756796-a43ef280-84d5-11e9-8363-4acc4c745587.png)

**Comment by icinsight** [comment]
8 decimals in 0xBitcoin token. I used "8" in tokens_metadata file. Trying "18" didn't solve the issue, obviously. https://etherscan.io/token/0xb6ed7644c69416d67b522e20bc294a9a9b405b31

**Comment by icinsight** [comment]
I added DGD, a 9 decimal token, as one more option. As seen before, numbers are 9 decimals too big. Orders were for 0.1 and 0.25 DGD. Also, I have some DGD in the wallet, but Balance shows 0.00.

![image](https://user-images.githubusercontent.com/39129866/58767420-1872a800-8561-11e9-9da6-13b50889eccb.png)

**Comment by tomhschmidt** [comment]
Wow, this is really bad. Huge potential for misleading order creation / fills.

**Comment by willwarren89** [comment]
Definitely an oversight, thank you for bringing this to our attention @icinsight.

**Comment by alessiofx** [comment]
I have same problem whit the crypto 2 decimals

**Comment by unjapones** [comment]
This should be now fixed in `development`. It ended up being a little bit trickier than we originally thought because of the `price` abstraction the UI handles. 

I remember that other UI/relayers like Bamboo presented a more verbosed form in the UI that let you enter the maker & taker amounts. That design is absolutely more explicit but it also forces the user to do the math :grimacing:
