### ISSUE TITLE
Estimate wait times are too long (120 sec)

### ISSUE THREAD

**Issue by mariano-aguero** [0xProject/0x-launch-kit-frontend#524]
Transaction estimated time is fetched from https://ethgasstation.info.
If any error happens while fetching this estimation the UI will set/show of 120 secs transaction time (arbitrary value, based on an example value from Instant).

The issue covers improving the robustness to prevent requests being throttled.

**Comment by unjapones** [comment]
UPDATE: although we merged a little improvement-PR, the feature is working as expected:

- In mainet we get the transaction time estimated.
- Other networks, show the time we retrieve for mainnet (:grimacing:).
- If any error happens, show the default 120s.

We asked internally how this error came up but didn't get much more info. Probably it makes sense to close this issue or change its priority.
