### ISSUE TITLE
Markets menu closes in an annoying way

### ISSUE THREAD

**Issue by icinsight** [0xProject/0x-launch-kit-frontend#553]
Open -> Click "LIRA/ZXB" -> Select "DAI" markets.

![image](https://user-images.githubusercontent.com/39129866/59982068-11303e80-95e3-11e9-8e98-2a675be5d3ac.png)

Click. The menu CLOSES!?? Bad!

![image](https://user-images.githubusercontent.com/39129866/59982077-286f2c00-95e3-11e9-9f58-1a5ee5ba6111.png)

Click "LIRA/ZXB" again to open menu because it is closed now. It opens. Now "DAI" markets are on.

![image](https://user-images.githubusercontent.com/39129866/59982083-37ee7500-95e3-11e9-93fc-a2a7479b3587.png)

**Comment by dekz** [comment]
@icinsight can't seem to repro this. Can you show me in a gif?

**Comment by icinsight** [comment]
![chrome-capture](https://user-images.githubusercontent.com/39129866/60194040-05c15b00-980f-11e9-87db-2f49adb1b388.gif)

**Comment by dekz** [comment]
Ok that's pretty weird.

![dropdown](https://user-images.githubusercontent.com/27389/60224293-28ae4680-98c5-11e9-9ab2-09349e50fdf3.gif)


Any chance you could try it out with the config file in #555?

**Comment by adekbadek** [comment]
Can't reproduce it either, I've checked on:
- Chrome 75.0.3770.100
- Safari 12.1
- Firefox 64.0.2

**Comment by icinsight** [comment]
This problem went away with latest updates.
