### ISSUE TITLE
Orderbook looks different before & after you connect your wallet

### ISSUE THREAD

**Issue by chriskalani** [0xProject/0x-launch-kit-frontend#554]
Wallet locked:

<img width="1531" alt="Screen Shot 2019-06-24 at 4 45 57 PM" src="https://user-images.githubusercontent.com/263522/60059042-a42eae80-969f-11e9-8ae7-4ad7213afc41.png">

**Wallet connected:**

<img width="1526" alt="Screen Shot 2019-06-24 at 4 46 06 PM" src="https://user-images.githubusercontent.com/263522/60059043-a4c74500-969f-11e9-9803-04435ce38354.png">

**Comment by dekz** [comment]
![image](https://user-images.githubusercontent.com/27389/60176111-b869db80-9858-11e9-888a-ab100506863f.png)

hmm maybe this is to do with decimal differences?
