### ISSUE TITLE
Add "Fee" field of "Order Details" in buy/sell component (when in Limit)

### ISSUE THREAD

**Issue by fvictorio** [0xProject/0x-launch-kit-frontend#58]
Use the maker and taker fees along with the order price to compute the total fee in ETH.

After this is done, we should add some mechanism for obtaining the price of ETH in USD.

- [ ] Show fee details in ETH
- [ ] Show fee details in USD

**Comment by unjapones** [comment]
*UPDATE 07 March 2019:*
Last week we spoke about this with the team and we realized that the user would probably like to see the fee in ZRX (because the will require ZRX in his/her balance, not ETH...]) + some user-friendly conversion of that fee value to USD.

**Comment by unjapones** [comment]
*UPDATE 07 March 2019:*
Decided to tackle the "Order Details" in 4 different issues:
* 2 tickets to "implement Fee" and "Total Cost" in LIMIT.
* 2 tickets for the same in MARKET.
