### ISSUE TITLE
Automatic UI Update Improvement

### ISSUE THREAD

**Issue by Agupane** [0xProject/0x-launch-kit-frontend#87]
Check if is necesary to use polling in order to receive the user account changed / networks events on wallets like nifty wallet. The current implementation uses events and it's supported on metamask but not tested on nitfy wallet.

Based on the comment: https://github.com/0xProject/0x-launch-kit-frontend/pull/84#discussion_r261593322

**Comment by pablofullana** [comment]
IMO, let's support just Metamask for now. I don't see any benefits in adding more code in this initial iteration just to support a wallet that's not as mainstream as MM, specially because of upcoming deadlines.
